site_name: pyRE - python package for non-life reinsurance pricing
theme:
  name: material
  palette:
    primary: teal
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - admonition