site_name: pyRE - python package for non-life reinsurance pricing
theme:
  name: material
  palette:
    primary: teal
  highlightjs: true
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.arithmatex
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home: index.md
  - Claims: claims.md
  - Exposures: exposures.md
  - Models: models.md
  - Treaty: treaty.md
  - Rate Monitoring: rate_monitoring.md
  - About: about.md
